steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      # app params
      - 'PORT=\${_PORT}'
      # spotify params
      - 'SPOTIFY_CLIENT_ID=\${_SPOTIFY_CLIENT_ID}'
      - 'SPOTIFY_CLIENT_SECRET=\${_SPOTIFY_CLIENT_SECRET}'
      - 'SPOTIFY_CALLBACK=\${_SPOTIFY_CALLBACK}'
      # guaqb music api params
      - 'GUAQB_KEY=\${_GUAQB_KEY}'
      - 'GUAQB_SECRET=\${_GUAQB_SECRET}'
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
